# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30edc6622f66f1780bbad2365ea2de45f7e79353e0770a6849be386f504688a9661bdee989c7955c0cb39bb355d4b82b2a640042616056927e3d28e0fa840903

test:
  secret_key_base: af29f2aefd28dd5e4f6a8089b0611be4066bf20b5b36122964d19ed10f88e6a35cf3569b83aca7cc655fdcde2a2d258b076fcd96d242da7bc5e848b8bf6d233d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
